# https://github.com/banyan/auto-label

name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'conc-pipeline/*'
    types:
      - opened
      - reopened

jobs:
  # Label the PR as described in '.github/labeler.yml'
  autolabeler_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Auto Labeler Step
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
