name: Auto Approve Workflow

on: 
  pull_request:
    paths-ignore:
      - 'and_another_dir/*'
      - 'just_another_dir/*'
      - 'actions_examples/*'
      - '.github/*'
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  autoapprove_job:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Step
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"




