name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'conc-pipeline/*'
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  autoapprove_job:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Step
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

  autolabeler_job:
    runs-on: ubuntu-latest
    needs: autoapprove_job
    steps:
    - uses: actions/checkout@v1
    - name: Auto Labeler Step
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  autorebasemerge_job:
    runs-on: ubuntu-latest
    needs: autolabeler_job
    steps:
      - uses: actions/checkout@v1
      - name: Auto Rebase and Merge Step 
        uses: "pascalgn/automerge-action@a7a731467672c853f76342a06615311a787d5591"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"


