name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'conc-pipeline/*'

jobs:
  autoapprove_job:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Step
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"


  # Label the PR as described in '.github/labeler.yml'
  autolabeler_job:
    needs: autoapprove_job
    runs-on: ubuntu-latest
    steps:
    - name: Auto Labeler Step
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  autorebasemerge_job:
    needs: autolabeler_job
    runs-on: ubuntu-latest
    steps:
      - name: Auto Rebase and Merge Step 
        uses: "pascalgn/automerge-action@a7a731467672c853f76342a06615311a787d5591"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
