name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'dir1/**'
      - 'dir2/**'
    types:
      - opened
      - edited
      - reopened

jobs:
  verify_modified_files_job:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Modified Files Step
      run: |
          # Example: LIST_OF_ONLY_DIRS_TO_BE_MODIFIED="dir1 dir2 dir3 ..."
          export LIST_OF_ONLY_DIRS_TO_BE_MODIFIED="dir1 dir2"

          echo
          echo
          echo  " List of files that were modified outside of \"$LIST_OF_ONLY_DIRS_TO_BE_MODIFIED\" dir(s):"
          echo

          # Once the file outside allowed dir is found, exit: this PR can't be automatically approved
          for allowed_dir in $LIST_OF_ONLY_DIRS_TO_BE_MODIFIED
          do
            if 
              curl --request GET \
              --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
              grep filename | \
              grep -v ${allowed_dir}
            then
              echo
              echo
              echo "  ERROR: PR can not be Auto Approved, as files outside of allowed \"$LIST_OF_ONLY_DIRS_TO_BE_MODIFIED\" dir(s) list were modified. See the list above."
              echo
              echo
              exit 8
            else
              echo
              echo
              echo "  CONFIRMED: The list above is empty. Thus, PR can be Auto Approved, as no files outside of \"$LIST_OF_ONLY_DIRS_TO_BE_MODIFIED\" dir(s) list were modified."
              echo
              echo
            fi
          done

  autoapprove_job:
    needs: verify_modified_files_job
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Step
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"




