name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'conc-pipeline/**'
    types:
      - synchronize
      - opened
      - edited
      - reopened

# jobs:
#   one:
#     runs-on: ubuntu-16.04
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Dump job context
#         env:
#           JOB_CONTEXT: ${{ toJson(job) }}
#         run: echo "$JOB_CONTEXT"
#       - name: Dump steps context
#         env:
#           STEPS_CONTEXT: ${{ toJson(steps) }}
#         run: echo "$STEPS_CONTEXT"
#       - name: Dump runner context
#         env:
#           RUNNER_CONTEXT: ${{ toJson(runner) }}
#         run: echo "$RUNNER_CONTEXT"
#       - name: Dump strategy context
#         env:
#           STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#         run: echo "$STRATEGY_CONTEXT"
#       - name: Dump matrix context
#         env:
#           MATRIX_CONTEXT: ${{ toJson(matrix) }}
#         run: echo "$MATRIX_CONTEXT"


jobs:
  is_pr_for_other_files_too:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        export ONLY_DIR_TO_BE_MODIFIED="conc-pipeline"

        if 
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
          grep filename | \
          grep -v $ONLY_DIR_TO_BE_MODIFIED
        then
          echo
          echo "  ERROR: The PR can not be Auto Approved, as \"$ONLY_DIR_TO_BE_MODIFIED\" is not the only directory that was modified."
          echo
          exit 88
        else
          echo
          echo "  CONFIRMED: The PR can be Auto Approved, as \"$ONLY_DIR_TO_BE_MODIFIED\" is the only directory that was modified."
          echo
        fi


  # autoapprove_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Auto Approve Step
  #     uses: hmarr/auto-approve-action@v2.0.0
  #     with:
  #       github-token: "${{ secrets.GITHUB_TOKEN }}"




