name: Auto Approve Workflow

on: 
  pull_request:
    paths:
      - 'conc-pipeline/*'
      - '!and_another_dir/*'
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  autoapprove_job:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Step
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"




