# https://github.com/actions/labeler

name: Auto Labeler
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    paths:
      - 'conc-pipeline/*'
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"


