# https://github.com/actions/labeler

name: Auto Labeler Workflow
on:
  pull_request:
    types:
      - opened
    paths:
      - 'conc-pipeline/*'

jobs:
  # Label the PR as described in '.github/labeler.yml'
  autolabeler_job:
    needs: autoapprove_job
    runs-on: ubuntu-latest
    steps:
    - name: Auto Labeler Step
      uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"


