# https://github.com/actions/labeler

name: Auto Labeler
on:
  pull_request:
    types:
      - opened
    paths:
      - 'conc-pipeline/*'

jobs:
  # Label the PR as described in '.github/labeler.yml'
  label_the_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"


