name: Auto Merge Workflow

on:
  check_suite:
    types:
      - completed
  # pull_request:
  #   paths:
  #     - 'dir1/**'
  #     - 'dir2/**'
  #   types:
  #     - labeled


jobs:

  autorebasemerge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Auto Rebase and Merge Step 
        uses: "pascalgn/automerge-action@a7a731467672c853f76342a06615311a787d5591"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
