# https://github.com/pascalgn/automerge-action

name: Auto Rebase and Merge 
on:
  pull_request:
    types:
      - labeled
    paths:
      - 'conc-pipeline/*'
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@a7a731467672c853f76342a06615311a787d5591"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
