name: Auto Merge Workflow

on:
  pull_request:
    paths:
      - 'conc-pipeline/*'
    types:
      - labeled
      - ready_for_review
      - synchronize

jobs:

  autorebasemerge_job:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Rebase and Merge Step 
        uses: "pascalgn/automerge-action@a7a731467672c853f76342a06615311a787d5591"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
