name: Auto Approve, Rebase, Delete Branch
on: 
  pull_request:
    paths:
      - 'conc-pipeline/*'

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
    - name: Automatic Approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Automatic Rebase
      uses: docker://ppnp/rebase_to_del:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Automatic Branch Removing After Its Rebase
    #   uses: jessfraz/branch-cleanup-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}