# https://github.com/marketplace/actions/wait-for-check

name: Main Auto Flow

on: 
  pull_request:
    paths:
      - '*.txt'
    types:
      - opened
      - edited
      - reopened

jobs:

  main_job:
    runs-on: ubuntu-latest
    steps:

      - name: Get statuses list manually
        run: |
              echo
              echo  "Statuses are:"
              echo
              # Get statuses list on current PR
              curl --request GET --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.head_ref }}

              PR_STATUS_NAME_EXPECTED="checkname"

              echo 
              echo "  Wait for necessary PR status ..."
              echo
              i=0
              while [[ "${NECESSARY_STATUS}z" == "z" ]]
              do
                  echo "      waiting ... $i"
                  i=`echo $(( $i + 1 ))`
                  sleep 10
                  if 
                  curl --request GET --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.head_ref }} | grep context | grep ${PR_STATUS_NAME_EXPECTED} > /dev/null 2>&1
                  then
                      NECESSARY_STATUS="present"
                  fi 
              done
              echo 
              echo "  Necessary PR status found."
              echo       



      # - uses: actions/checkout@v1

      # - name: Wait for build to succeed
      #   uses: fountainhead/action-wait-for-check@v1.0.0
      #   id: wait-for-build
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     checkName: checkname
      #     ref: github.event.pull_request.head.sha || github.sha
      #     # ref: github.sha
      #     # intervalSeconds: 10

      # - name: What if it's SUCCESS?
      #   if: steps.wait-for-build.outputs.conclusion == 'success'
      #   run: |
      #        echo
      #        echo  "I can see that status of the Additional Job:   OK"
      #        echo

      # - name: What if it's FAIL?
      #   if: steps.wait-for-build.outputs.conclusion == 'failure'
      #   run: |
      #        echo
      #        echo  "I can see that status of the Additional Job:   FAIL"
      #        echo
      #        exit 4
