# https://github.com/marketplace/actions/wait-for-check

name: Main Auto Flow

on: 
  pull_request:
    paths:
      - '*.txt'
    types:
      - opened
      - edited
      - reopened

jobs:

  main_job:
    runs-on: ubuntu-latest
    steps:

      # - name: Sleep for a few seconds
      #   run: |
      #         SEC=10
      #         echo
      #         echo  "Sleeping for a ${SEC} sec"
      #         echo
      #         sleep ${SEC}

      - uses: actions/checkout@v1

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: checkname
          ref: github.event.pull_request.head.sha || github.sha
          # ref: github.sha
          # intervalSeconds: 10

      - name: What if it's SUCCESS?
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
             echo
             echo  "I can see that status of the Additional Job:   OK"
             echo

      - name: What if it's FAIL?
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: |
             echo
             echo  "I can see that status of the Additional Job:   FAIL"
             echo
             exit 4
