# https://github.com/marketplace/actions/wait-for-check

name: Main Auto Flow

on: 
  pull_request:
    paths:
      - '*.txt'
    types:
      - opened
      - edited
      - reopened

jobs:

  statjob2:
    runs-on: ubuntu-latest
    steps:
    - name: this step could be Successfull or Not
      run: |
            echo  "Status of the Job:   OK"
            # echo  "Status of the Job:   FAIL"
            # exit 3

  main_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: statjob2
          ref: github.event.pull_request.head.sha || github.sha
          # ref: github.sha
          intervalSeconds: 15

      - name: What if it's SUCCESS?
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
             echo
             echo  "I can see that status of the Additional Job:   OK"
             echo

      - name: What if it's FAIL?
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: |
             echo
             echo  "I can see that status of the Additional Job:   FAIL"
             echo
             exit 4
